[project]
name = "wrapped"
version = "0.1.0"
description = "This compiles the statistics for spotify wrapped."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "python-dotenv>=1.0.1",
    "spotipy>=2.25.0",
]
